name: 'Git-Semver Setup Action'
description: 'Performs setup of psanetra/git-semver for use in other GitHub workflows'
author: 'Roger Barker <pendletonroger@gmail.com>'
branding:
  icon: 'check-circle'
  color: 'blue'

inputs:
  version:
    description: 'The version of git-semver to use'
    required: false
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - name: Install go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version: '1.24.2'

    - name: Clone and build git-semver
      shell: bash
      run: |
        if [[ "${{ inputs.version }}" == "latest" ]]; then
          # clone the latest version
          git clone --depth 1 https://github.com/PandasWhoCode/git-semver.git
          cd git-semver
          git fetch origin 4af2d24294f6fb4de5584f4f5c7cd4d29b609909 # v0.2.7
          git checkout 4af2d24294f6fb4de5584f4f5c7cd4d29b609909 # v0.2.7
          cd ..
        else
          # clone the specified version
          git clone --branch ${{ inputs.version }} https://github.com/PSanetra/git-semver.git
        fi
        
        cd git-semver/cli
        go build -o git-semver
        sudo mv git-semver /usr/local/bin
